project_id = "espsuvikygescxznequn"

[functions.create-order]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.get-download-url]
verify_jwt = true
