import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import type { Json } from '@/integrations/supabase/types';
import { orderSchema } from '@/lib/validations';

export interface OrderAddress {
  id: string;
  address_line1: string;
  address_line2: string | null;
  city: string;
  state: string;
  country: string;
  postal_code: string | null;
}

export interface Order {
  id: string;
  order_number: string;
  status: string;
  payment_status: string;
  subtotal: number;
  shipping_cost: number;
  total: number;
  address_id: string | null;
  shipping_address: Record<string, unknown> | null; // Deprecated: kept for backward compatibility
  payment_reference: string | null;
  notes: string | null;
  created_at: string;
  customer?: {
    id: string;
    email: string;
    full_name: string | null;
    phone: string | null;
  } | null;
  address?: OrderAddress | null;
  order_items?: Array<{
    id: string;
    product_name: string;
    variant_name: string | null;
    quantity: number;
    unit_price: number;
    total_price: number;
    is_digital: boolean;
  }>;
}

export const useOrders = () => {
  const { isAdmin } = useAuth();

  return useQuery({
    queryKey: ['orders', isAdmin],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          customer:customers(id, email, full_name, phone),
          address:addresses(id, address_line1, address_line2, city, state, country, postal_code),
          order_items(*)
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as Order[];
    },
    enabled: isAdmin,
  });
};

export const useUpdateOrderStatus = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ orderId, status }: { orderId: string; status: string }) => {
      const { error } = await supabase
        .from('orders')
        .update({ status })
        .eq('id', orderId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
};

export const useCreateOrder = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (orderData: {
      customerId: string;
      items: Array<{
        productId: string;
        variantId?: string;
        productName: string;
        variantName?: string;
        quantity: number;
        unitPrice: number;
        isDigital: boolean;
      }>;
      subtotal: number;
      shippingCost: number;
      total: number;
      shippingAddress?: {
        address_line1: string;
        address_line2?: string;
        city: string;
        state: string;
        country?: string;
        postal_code?: string;
      };
    }) => {
      // Validate order data with zod before sending to database
      const validation = orderSchema.safeParse(orderData);
      if (!validation.success) {
        const errors = validation.error.errors.map(e => e.message).join(', ');
        throw new Error(`Validation failed: ${errors}`);
      }

      let addressId: string | null = null;

      // Create address in the addresses table if provided
      if (orderData.shippingAddress) {
        const { data: address, error: addressError } = await supabase
          .from('addresses')
          .insert([{
            customer_id: orderData.customerId,
            address_line1: orderData.shippingAddress.address_line1,
            address_line2: orderData.shippingAddress.address_line2 || null,
            city: orderData.shippingAddress.city,
            state: orderData.shippingAddress.state,
            country: orderData.shippingAddress.country || 'Nigeria',
            postal_code: orderData.shippingAddress.postal_code || null,
          }])
          .select()
          .single();

        if (addressError) throw addressError;
        addressId = address.id;
      }

      // Create order - order_number will be generated by database trigger
      const tempOrderNumber = `ORD-${Date.now()}`;
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert([{
          order_number: tempOrderNumber,
          customer_id: orderData.customerId,
          subtotal: orderData.subtotal,
          shipping_cost: orderData.shippingCost,
          total: orderData.total,
          address_id: addressId,
        }])
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items with validated data
      const orderItems = orderData.items.map(item => ({
        order_id: order.id,
        product_id: item.productId,
        variant_id: item.variantId || null,
        product_name: item.productName.slice(0, 255), // Enforce length limit
        variant_name: item.variantName?.slice(0, 255) || null,
        quantity: Math.max(1, Math.floor(item.quantity)), // Ensure positive integer
        unit_price: Math.max(0, item.unitPrice),
        total_price: Math.max(0, item.unitPrice) * Math.max(1, Math.floor(item.quantity)),
        is_digital: item.isDigital,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      return order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
};